export const cityData = {
  "cities": [
    {
      id: 1,
      city: "Austin",
      state: "Texas",
      city_and_state: "Austin, TX",
      image: "https://i.postimg.cc/DZSv4JMJ/austin.jpg",
      num_on_best_paying_cities_list: 16,
      median_software_developer_salary_adj: 108990,
      median_income_of_all_jobs: 53810,
      num_software_developer_jobs: 21160,
      median_home_price: 311300,
      big_companies: ["IBM", "Dell", "Home Depot", "Deloitte", "Charles Schwab"],
      population_2019: 979908,
      population_change_since_2020: "\"+49.1%\"",
      city_blurb: "Austin has done it again. The Austin-Round Rock metro area is holding steady at No. 1 on the Tech Town Index—its second year in a row in the top spot, rising from No. 3 in 2018. In 2018, we reported 46 tech company relocations to Austin. In 2019, that number increased to 58, according to the Austin Chamber of Commerce, which translated to 4,648 new jobs. Those numbers align with CompTIA’s findings, which show 68,323 IT jobs posted between August 2019 and July 2020—an increase of more than 19,000 over last year. </br> Of course, with exponential growth comes exponential capital. Crunchbase data claims Austin experienced record venture funding in 2019, with local startups raising $1.84 billion for the year, up 19.5% compared to the $1.54 billion raised in 2018, and an impressive 87% increase compared to $983 million in 2017. </br> Where are these companies coming from? Experts say that Austin has become a favorable alternative to the Bay Area and New York City for companies of all sizes that are looking to grow. In fact, the Austin-Round Rock area is home to 5,500 startups and tech companies—leading to many dubbing it the “Silicon Hills.” Google, Facebook, Atlassian and Oracle have thousands of workers in Austin and Apple is making the move to North Austin as well—with potential to add 15,000 more workers to its existing 7,000. </br> Even amid the latest technology boom, the Austin metro area remains one of best places to live in terms of cost of living. Keeping below the national average by about 4%, Austin continues to flex its muscle when it comes to affordability. In fact, there are only three other cities on this list that fare better (Columbus, Atlanta and Huntsville). That’s a bonus for IT pros who earn a median salary of $87,880 here. </br> With major tech players and startups alike calling Austin home, along with great schools, a thriving nightlife and an active, outdoor lifestyle, it’s no surprise that the city has been named the fastest-growing major metro area in the U.S.—and is the reigning No. 1 Tech Town.\n\n"
    },
    {
      id: 2,
      city: "Dallas",
      state: "Texas",
      city_and_state: "Dallas, TX",
      image: "https://i.postimg.cc/3rDrKGGz/dallas.jpg",
      num_on_best_paying_cities_list: 12,
      median_software_developer_salary_adj: 110891,
      median_income_of_all_jobs: 52590,
      num_software_developer_jobs: 46130,
      median_home_price: 243900,
      big_companies: ["Lockhead Martin", "JPMorgan Chase", "USAA", "Citi", "Deloitte"],
      population_2019: 1343573,
      population_change_since_2020: "\"+13.0%\"",
      city_blurb: "Jumping from No. 7 last year (and No. 6 in 2018), the sheer number of IT jobs available in Dallas is one of the key reasons for the bump. In the past 12 months, 178,579 IT jobs were posted in the Dallas metro area, including Fort Worth and Arlington. Compared to 146,388 IT jobs posted last year (133,778 at the time of publish), the nearly 32,000+ new jobs posted are proof of the rapid growth potential here. </br> Lockheed Martin and JPMorgan Chase posted the most IT jobs between August 2019 and July 2020. But web, mobile application and software development have formed the core of the IT enterprise ecosystem of the city. In short, the conventional technology enterprises have set the tone for the Dallas tech scene while emerging technology companies are taking it to the next level. </br> IT job growth in the Dallas metro area is expected to grow by 3% to about 176,000 jobs from 2020 to 2021, and by a whopping 11% in the next five years to nearly 190,000 jobs. With the cost of living 2% lower than the U.S. average, more and more young people are putting down roots in this area. With a median IT salary of $94,044, plenty of live music and professional sports teams, tech professionals are finding opportunity and quality of life in Dallas."
    },
    {
      id: 3,
      city: "Raleigh",
      state: "North Carolina",
      city_and_state: "Raleigh, NC",
      image: "https://i.postimg.cc/mgsYpc6x/raleigh.jpg",
      num_on_best_paying_cities_list: 17,
      median_software_developer_salary_adj: 107676,
      median_income_of_all_jobs: 52580,
      num_software_developer_jobs: 12560,
      median_home_price: "267200",
      big_companies: ["IBM", "Wells Fargo", "Red Hat", "Metropolitan Life Insurance", "SAS Institute"],
      population_2019: 474069,
      population_change_since_2020: "\"+71.7%\"",
      city_blurb: "Raleigh is and affordable city overflowing with in-demand tech talent. At least that’s what hatch I.T. found when conducting a talent market analysis for a client looking for the optimal location to open another office. Located in the North Carolina Research Triangle, Raleigh is a major east coast tech hub, which explains why it has consistently placed in the top 3 on the index every year. This year, slightly falling from No. 2 to No. 3, Raleigh remains tough to beat. </br> The fact is that talent in this area flock to the startups and the startups need the talent. With multiple universities, including NC State, and plenty of community colleges within throwing distance, a qualified workforce is at the ready. Forbes recently reported that NC State is ranked No. 10 in the nation for entrepreneurship due to its unique programs like the Entrepreneurship Garage and the Entrepreneurship Clinic where students work side-by-side with real-world startups. Over the past five years, NC State has produced more than 170 university startups attracting $1.7 billion in venture capital. </br> And you don’t have to empty your savings to put down roots here. The cost of living in Raleigh is about 4% lower than the national average, with IT pros being paid a median salary of $93,781. The cost of living per month for one person in Raleigh is $2,743. For comparison, Washington, D.C., is $5,206. And that works both ways. Companies doing business in Raleigh enjoy lower operational costs as well."
    },
    {
      id: 4,
      city: "San Jose",
      state: "California",
      city_and_state: "San Jose, CA",
      image: "https://i.postimg.cc/3NZ1KW2f/san-jose.jpg",
      num_on_best_paying_cities_list: 27,
      median_software_developer_salary_adj: 104964,
      median_income_of_all_jobs: 80480,
      num_software_developer_jobs: 78730,
      median_home_price: 1193600,
      big_companies: ["Apple", "NVIDIA", "VMware", "Cisco", "Amazon"],
      population_2019: 1021795,
      population_change_since_2020: "\"+14.2%\"",
      city_blurb: "The San Jose metro area consistently ranks in the top 5 on the Tech Town Index year after year. This year, falling just a bit to No. 4, San Jose, Sunnyvale and Santa Clara are becoming sought after locales for IT pros for other reasons—namely the pandemic. </br> Data analytics firm Moody found that San Jose may be the city in the best position to welcome an influx of residents fleeing congested cities (like San Francisco) post-COVID-19. In actuality, San Jose has a larger population than its neighbor, San Francisco. But it also has approximately 176 square miles (vs. 49 square miles) to accommodate its residents, giving the area a more suburban feel. And as tech pros adjust to work-from-home policies, the affordability factor becomes even more attractive. </br> Of course, affordability is all relative. Living in San Jose may mean sunshine and access to the Bay, but it also means forking over more of your salary for cost of living expenses. For example, according to Zillow, the median home value in the San Jose area is $1,073,255. While that may seem exorbitantly high, the cost of living in San Francisco is actually higher. IT pros in San Jose are paid a median salary of $137,100, but adjusted for cost of living expenses, that’s really about $93,266. </br> However, with 134,971 IT jobs advertised for in the last year (down from 151,778 in the previous year), the San Jose area is still poised for growth. In fact, jobs are expected to grow by 3% in one year and by 11% in the next five years—numbers that have certainly factored into San Jose's consistently high ranking on the Tech Town Index."
    },
    {
      id: 5,
      city: "Charlotte",
      state: "North Carolina",
      city_and_state: "Charlotte, NC",
      image: "https://i.postimg.cc/sXHzVjfj/charlotte.jpg",
      num_on_best_paying_cities_list: 5,
      median_software_developer_salary_adj: 114122,
      median_income_of_all_jobs: 51000,
      num_software_developer_jobs: 12800,
      median_home_price: 208500,
      big_companies: ["Wells Fargo", "Bank of America", "Lowe's", "IBM", "Deloitte"],
      population_2019: 885708,
      population_change_since_2020: "\"+63.8%\"",
      city_blurb: "Charlotte’s traditional strength as a banking hub has provided the foundation for the region’s economic success. As companies continue to embrace technology, the financial sector included, the city has seen an influx of 68% more tech workers in the past decade, according to the Charlotte Regional Business Alliance. Charlotte made its debut at the top of the Tech Town Index in 2018, and while it has fallen a bit in rank, the diversifying tech scene continues to drive the economy in this desirable region. </br> The Charlotte Regional Business Alliance reports that more than 52,000 core high-tech talent workers live and work in Charlotte with nearly 35% of tech talent working for corporate headquarters, finance and insurance, or consulting services. Another 35% of IT pros work for core tech industries like software publishers and computer systems design services—a growing market. </br> The Tech Town data supports this growth. In the past 12 months, the Charlotte metro area has advertised for 81,081 technology jobs—as compared to 57,358 in the previous year. More than 40 fintech firms are located here, including unicorn payments automation company AvidXchange and industry pioneer LendingTree. And, Lowe’s recently selected Charlotte for its 2,000-employee global tech hub. </br> Things aren’t expected to slow down. In five years, it's predicted the region will see an 8% increase in tech jobs—not a surprise, considering this tech hub is located in one of the most affordable (and beautiful) areas of the country. The cost of living in Charlotte is approximately 2% lower than the national average with median home prices hovering around $262,000, according to Zillow. IT pros in the area make a median salary of $91,612, which equates to more disposable income."
    },
    {
      id: 6,
      city: "Seattle",
      state: "Washington",
      city_and_state: "Seattle, WA",
      image: "https://i.postimg.cc/26gzQksH/seattle.jpg",
      num_on_best_paying_cities_list: 3,
      median_software_developer_salary_adj: 117323,
      median_income_of_all_jobs: 65400,
      num_software_developer_jobs: 65760,
      median_home_price: 491600,
      big_companies: ["Amazon", "Microsoft", "Oracle", "Facebook", "Deloitte"],
      population_2019: 753675,
      population_change_since_2020: "\"+33.8%\"",
      city_blurb: "Falling two spots to No. 6, versus No. 4 last year, the Seattle metro area continues to be a national hub for STEM jobs, GDP growth and venture capital investments. Notably one of the regions impacted the most by COVID-19, the Seattle area still shows a demand for technology jobs—90,573 posted this past year as compared to 93,229 in the previous year. </br> According to the Seattle Tech Ecosystem Report, authored jointly by the Innovate Leadership Network and the University of Washington Bothell, the information, communications and technology sector grew faster than any other sector of Greater Seattle’s innovation economy this year. Amazon and Microsoft continue to grow their footprint in Seattle and big tech powerhouses like Salesforce, Google, Apple, Facebook and others are expanding here as well. </br> In fact, tech jobs are expected to grow by 11% over the next five years in the Seattle metro area and IT pros are taking notice. According to Redfin search data, the Seattle-Tacoma area is one of the top locations people in the Bay Area are considering for a move. It could be the area, but it also could be the compensation that's a draw for IT pros. Technology workers in Seattle earn a median annual salary of $125,318. And although the cost of living is 22% higher than the national average here, the extra cost may be worth it. Seattle ranks No. 1 on our list when salaries are adjusted for cost of living, which means employers seem to recognize the expense associated with living in the area and compensate employees accordingly."
    },
    {
      id: 7,
      city: "San Francisco",
      state: "California",
      city_and_state: "San Francisco, CA",
      image: "https://i.postimg.cc/L57jBQnG/san-francisco.jpg",
      num_on_best_paying_cities_list: 10,
      median_software_developer_salary_adj: 111017,
      median_income_of_all_jobs: 72400,
      num_software_developer_jobs: 59550,
      median_home_price: 946700,
      big_companies: ["Amazon", "Facebook", "Wells Fargo", "Deloitte", "Salesforce"],
      population_2019: 881549,
      population_change_since_2020: "\"+13.5%\"",
      city_blurb: "With rumors of a San Francisco mass exodus swirling during the pandemic due to the advent of long-term remote work, the San Francisco metro area dropped to No. 7 on our list this year—just out of top 5 territory. While this isn’t really a new story (every year survey results suggest that people plan to move away from San Francisco), the numbers are actually on the rise. The California Department of Finance reports that the population has increased by more than 6,700 in the last year. </br> In the past 12 months, the combined areas of San Francisco, Oakland and Hayward posted a total of 168,495 technology jobs. And although the Bay Area tech mecca is the ultimate destination for many young dreamers, the reality is that having a high-tech salary in the nation's most competitive real estate market doesn't always meet expectations. It's no surprise that cost of living is the big story here. San Francisco ranks dead last on our list when it comes to affordability. In fact, the cost of living is a whopping 67% higher than the national average. For example, according to an article in Business Insider, a one-bedroom apartment in the area runs an average of $3,550 per month. </br> But San Francisco has its reputation to lean on and growth is still imminent. In the next year, a 4% increase in tech jobs is expected, followed by a 13% increase over five years. That estimated increase in jobs is only topped by Austin. </br> In 2020, Silicon Valley employees voted Google as the most desirable company to work for, followed by Netflix, Slack, LinkedIn and Apple, according to a survey put out by job search marketplace Hired. Just how remote work will affect San Francisco post-pandemic remains to be seen. What we do know is that the area is still at the epicenter of tech and shouldn’t be counted out."
    },
    {
      id: 8,
      city: "Atlanta",
      state: "Georgia",
      city_and_state: "Atlanta, GA",
      image: "https://i.postimg.cc/2qk1rh3Q/atlanta.jpg",
      num_on_best_paying_cities_list: 14,
      median_software_developer_salary_adj: 109849,
      median_income_of_all_jobs: 52750,
      num_software_developer_jobs: 38110,
      median_home_price: 219600,
      big_companies: ["Deloitte", "IBM", "Anthem Blue Cross", "Home Depot", "Capgemini"],
      population_2019: 506811,
      population_change_since_2020: "\"+21.7%\"",
      city_blurb: "Newly nicknamed “The Silicon Valley of the South,” Atlanta has been quietly building a tech startup community that is poised to take the tech world by storm. And holding its position at No. 8 on the Tech Town Index illustrates how well that strategy is working. </br> Home to the Atlanta Tech Village, a self-described shared space to foster a collaborative community, the city is consistently named one of the country’s most desirable up-and-coming tech epicenters. But, that’s not enough for Atlanta. In fact, one of the goals of the Atlanta Tech Center is to transform Atlanta into a top five tech city—and they are hard at work. Atlanta Tech Village says it has launched more than 300 startups, created more than 6,500 jobs and its companies have raised more than $826 million in capital. </br> Technology jobs are certainly on the rise. In the past year, the metro area advertised for 113,935 IT jobs. In addition, the number of IT jobs is expected to grow by 8% over the next five years. The software and fintech markets are exploding, but the city has companies tackling everything from blockchain to health tech. And don't count out the Fortune 500 companies that call Atlanta home. There are 16 Fortune 500 companies headquartered in Atlanta, including The Home Depot, UPS and Coca-Cola. </br> However, there’s more to a Tech Town than its technology. Lifestyle plays an important part, and Atlanta ranks high in this category as well. The cost of living here is about 5% lower than the national average and local IT pros earn a median annual wage of $92,725. In an area where median home values sit at about $300,000, Atlanta’s affordability is tough to beat."
    },
    {
      id: 9,
      city: "Huntsville",
      state: "Alabama",
      city_and_state: "Huntsville, AL",
      image: "https://i.postimg.cc/kVTB4Gtk/huntsville.jpg",
      num_on_best_paying_cities_list: 1,
      median_software_developer_salary_adj: 120392,
      median_income_of_all_jobs: 54630,
      num_software_developer_jobs: 5920,
      median_home_price: 169500,
      big_companies: ["SAIC", "Norththrop Grumman", "Leidos", "Dynetics", "Boeing"],
      population_2019: 200574,
      population_change_since_2020: "\"+26.8%\"",
      city_blurb: "Once a best-kept secret, Huntsville, Alabama, is no stranger to the tech scene. In fact, the city is growing by leaps and bounds due to its strong technology roots, affordability and engaging lifestyle. Climbing one spot to No. 9 on our list this year, Huntsville proves you don’t have to live in a large city to enjoy the perks of a tech job. </br> Opportunity continues to flourish in this Southern town with more than 15,000 technology jobs advertised in Huntsville in the past year. IT jobs are expected to increase by 2% in the next year and by 8% over the next five years. Huntsville IT pros also enjoy a cost of living that is 4% lower than the national average. IT pros in this area earn a median salary of $97,316—which competes with annual salaries in Denver, Colorado Springs and Trenton, all cities with cost of living rates above the national average. </br> The city’s technology economy has historically been driven by its military presence. For example, Lockheed Martin is one of the biggest government contractors in the nation and active in Huntsville’s military-industrial complex. Last year, the company announced it would invest $19 million in new facilities and hire 200 people. Leidos is another Huntsville employer, active in defense, health and civilian technical areas. The company invested $3 million in Huntsville in 2019 and hired 88 new employees. Leidos also bought a local Huntsville company, Dynetics, for $1.6 billion. </br> But government contracts aren’t the only thriving opportunities here. Entrepreneurship and innovation are a critical part of the city’s economic diversification strategy. Its network of colleges and universities, federal and non-profit R&D labs, incubators and mentoring assistance organizations provide training and meetups for IT pros with a passion and an idea. Huntsville is also home to the WeRockIT Conference, an annual meeting that features all disciplines of technology and shows how they can all interconnect."
    },
    {
      id: 10,
      city: "Denver",
      state: "Colorado",
      city_and_state: "Denver, CO",
      image: "https://i.postimg.cc/5YjjFJBj/denver.jpg",
      num_on_best_paying_cities_list: 26,
      median_software_developer_salary_adj: 105197,
      median_income_of_all_jobs: 59440,
      num_software_developer_jobs: 26750,
      median_home_price: 407900,
      big_companies: ["Lockhead Martin", "Spectrum", "Charter", "Raytheon", "Deloitte", "CenturyLink"],
      population_2019: 727211,
      population_change_since_2020: "\"+31.1%\"",
      city_blurb: "Rounding out the top 10 is Denver, Colorado. The Colorado Office of Economic Development and Trade says it is Denver’s cultural similarities to the Bay Area coupled with an active outdoor lifestyle that attracts the heavyweights like Amazon and Google, along with hundreds of small and medium-sized startups. </br> True to its word, the Denver metro area posted nearly 80,000 jobs in the past 12 months—up over 8,000 from the previous year. The area claims that despite the uncertainty caused by COVID-19, tech is still on the rise—and our numbers support that. IT jobs are expected to grow by 3% in the next year and by 12% over the next five years. And although the cost of living is about 14% higher than the national average, it still falls well below the likes of Silicon Valley and offers just as much opportunity as the city develops incentives to attract new businesses. </br> In fact, two Denver tech businesses won federal grants to develop new products amid the pandemic. Greetly, which provides systems for companies to check-in and track visitors, received $50,000 through the Small Business Innovation Research (SBIR) program to work with the Air Force. Likewise, Cipher Skin won a $1.5 million grant from the Department of Defense through the SBIR program. Cipher Skin will match the grant and work with the Air Force to explore how the military can use and further develop its technology for civilian use, according to The Denver Post.\n\n"
    },
    {
      id: 11,
      city: "Washington",
      state: "District of Columbia",
      city_and_state: "Washington, DC",
      image: "https://i.postimg.cc/1VqtJKYQ/washington-dc.jpg",
      num_on_best_paying_cities_list: 47,
      median_software_developer_salary_adj: 101188,
      median_income_of_all_jobs: 70980,
      num_software_developer_jobs: 63760,
      median_home_price: 407700,
      big_companies: ["General Dynamics", "Leidos", "Booz Allen Hamilton", "SAIC", "CACI"],
      population_2019: 705749,
      population_change_since_2020: "\"+23.4%\"",
      city_blurb: "Once again, the name of the game in Washington, D.C., is jobs—and there are lots of them. Last year, the D.C. metro area topped our list with the sheer amount of technology jobs it had available. This year D.C. does it again. But this time, the amount of IT jobs advertised surpasses the previous year by about 34,000, with more than 260,000 postings this past year. </br> It’s no surprise that the government sector is the biggest factor here. However, it’s not the only one. Cybersecurity is an obvious close second. When you think about the sheer amount of sensitive digital data that goes through the city, the need for qualified cybersecurity professionals makes sense. Other areas of growth include software development and technical and digital solutions. In fact, within five years, the area is projected to see even more growth—up to 5% when it comes to jobs. And then there’s Amazon’s HQ2, a multi-year project that will technically reside in two locations between Arlington and Alexandria. The new development, which will serve as the massive online retailer’s base of operations on the East Coast, will reportedly employ 25,000 people—1,000 of which have been hired as of June 2020. According to Amazon, the company has no plans to downsize that number and is continuing to hire as planned. </br> Job growth aside, equally intriguing is the D.C. lifestyle. Chock full of diverse people from all over the world, the epicenter for politics and a rich history, the city is simply the place to be on the East Coast. And while the cost of living is 17% higher than the national average, earning the metro area a ranking of No. 12 when it comes to affordability, employers seem to take this into account when it comes to compensation. Local IT pros earn a median salary of $109,890 here. That's more than the median salary in San Diego for the sake of comparison."
    },
    {
      id: 12,
      city: "Boulder",
      state: "Colorado",
      city_and_state: "Boulder, CO",
      image: "https://i.postimg.cc/PNpPXtfR/boulder.jpg",
      num_on_best_paying_cities_list: 29,
      median_software_developer_salary_adj: "104630",
      median_income_of_all_jobs: "64690",
      num_software_developer_jobs: "6620",
      median_home_price: "534700",
      big_companies: ["Ball Corporation", "Lockhead Martin", "Amazon", "Sierra Nevada Corporation", "Northrop Grumman"],
      population_2019: 105673,
      population_change_since_2020: "\"+11.6%\"",
      city_blurb: "The results are in. Boulder, Colorado, is a rising global tech hub due to its self-sustaining ecosystem, its tech-focused resource pool and its notably intelligent population. Those are just a few reasons why Boulder has jumped two spots to No. 12 on the index this year. </br> Google and Twitter are mainstays in Boulder with each company investing $130 million and $125 million respectively back into the community. But it's also the home of startup incubator, Techstars, and a healthy venture capital community. With more than 10,000 technology jobs being advertised as up for grabs in the past year, and the fact that the number of IT jobs expected to grow by 10% over the next five years, it's no surprise that Boulder is being recognized as a rising tech hub. </br> Experts credit the tech boom in this idyllic mountain city to a few things. One, the City of Boulder and the Boulder Chamber of Commerce are incredibly helpful and tech-focused. For example, the Flexible Rebate Program invests in Boulder’s high impact primary employers if they plan to grow in town and make investments in facilities, employees and the like. Two, Boulder is ranked No. 1 in Bloomberg’s Brain Concentration Index, which is a breakdown of STEM degrees, amount of advanced degrees and new business formation. In short, Boulderites are proven smarties. </br> Local IT pros can earn a good living here, with a median salary of $102,294—although the cost of living is about 17% higher than the average, and land sells at a premium in an effort to preserve open spaces. But paying the premium in favor of the year-round outdoor quality of life the area offers is worth it to many."
    },
    {
      id: 13,
      city: "Durham-Chapel Hill",
      state: "North Carolina",
      city_and_state: "Durham-Chapel Hill, NC",
      image: "https://i.postimg.cc/9QC3TRn8/durham-chapel-hill.jpg",
      num_on_best_paying_cities_list: 13,
      median_software_developer_salary_adj: 110313,
      median_income_of_all_jobs: 59940,
      num_software_developer_jobs: 6800,
      median_home_price: "243700",
      big_companies: ["IBM", "IQVIA", "Cisco", "Fidelity", "Duke University"],
      population_2019: 278993,
      population_change_since_2020: "\"+49.2%\"",
      city_blurb: "Back in 1965, IBM made the move to the Research Triangle Park in order to invest in people that would grow the business. That decision has obviously paid off in more than one way, and today IBM remains a top employer in the area. Holding its place at No. 13 on the index, Durham-Chapel Hill continues to be a mainstay on the corporate relocation short list. </br> This region excels in the areas of interactive software and games, defense technologies, open source, software development and nanotechnology. The tech industry here currently accounts for nearly 50,000 jobs according to WorkInTheTriangle.com. In fact, the area posted 22,124 IT jobs in the past 12 months—an increase of nearly 3,500+ over the previous year. Furthermore, the number of IT jobs is expected to grow by 4% over the next five years. </br> Like neighboring Tech Town Raleigh, a big draw for tech companies in Durham-Chapel Hill is prime access to educated, qualified talent due to its sheer proximity to major universities, including Duke and University of North Carolina at Chapel Hill, as well as community colleges. For IT pros, a major upside is the cost of living. While the area is just about level with the national average, tech talent in the Triangle region make a median salary of $93,320 and enjoy the perks of a more affordable lifestyle, like lower home prices and property taxes."
    },
    {
      id: 14,
      city: "Columbus",
      state: "Ohio",
      city_and_state: "Columbus, OH",
      image: "https://i.postimg.cc/7h8tkjvs/columbus.jpg",
      num_on_best_paying_cities_list: 2,
      median_software_developer_salary_adj: 117552,
      median_income_of_all_jobs: 51260,
      num_software_developer_jobs: 13430,
      median_home_price: 192000,
      big_companies: ["JPMorgan Chase", "Accenture", "Cardinal Health", "IBM", "Huntington National Bank"],
      population_2019: 898553,
      population_change_since_2020: "\"+26.3%\"",
      city_blurb: "The Columbus region consists of 10 counties in Central Ohio and is home to 2.1 million people. It is the fastest growing metropolitan area in the Midwest. Maybe that’s why it is just one of two Midwest cities to make an appearance on the index this year. Coming in at No. 14 (down two spots from last year), the major investments in tech combined with the lowest cost of living on the index equate to a full-fledged Midwestern tech hub. </br> Tech experts and C-level executives are saying that Central Ohio has the right mix of talented people, groundwork and infrastructure that's attracting big names from Silicon Valley and across the world. Perhaps that's why tech jobs continue to see growth here. In the past year, Columbus posted 47,594 open tech jobs—up from 46,379 in the previous year. By a separate measure, IT jobs are expected to increase by 3% over the next five years. </br> Of course, while the influence of The Ohio State University and medical innovation at the Wexner Medical Center and Nationwide Children's Hospital are major points in the Columbus column for employers, it's the affordability and lifestyle that attract tech talent. The cost of living here is 6% lower than the national average. IT pros earn a median salary of $88,099. But, adjusted for the lower cost of living, that number is more like $93,226—comparable to actual earning for IT pros in Raleigh, Durham-Chapel Hill, Dallas and Trenton.\n\n"
    },
    {
      id: 15,
      city: "Colorado Springs",
      state: "Colorado",
      city_and_state: "Colorado Springs, CO",
      image: "https://i.postimg.cc/g2TDp18V/colorado-springs.jpg",
      num_on_best_paying_cities_list: 6,
      median_software_developer_salary_adj: 112118,
      median_income_of_all_jobs: 51430,
      num_software_developer_jobs: 5780,
      median_home_price: 296500,
      big_companies: ["Northrop Grumman", "Boeing", "Lockhead Martin", "SAIC", "LinQuest"],
      population_2019: 478221,
      population_change_since_2020: "\"+32.5%\"",
      city_blurb: "While Denver and Boulder may have higher rankings on the index, Colorado Springs is quietly elevating itself as an emerging tech hub in its own right. Climbing up one spot from last year (and five spots from 2018), No. 15 on the index is drawing the attention of tech’s biggest players, as well as small startups with big plans. </br> The Colorado Springs Chamber & EDC reports that the area is home to 140+ IT companies and 125+ cybersecurity companies. The metro area advertised for more than 16,000 technology jobs last year and as companies and investors continue to discover the area, the number of IT jobs is expected to grow an estimated 6% in next five years. In addition to a thriving IT industry, the Colorado Springs area has become a data center hotspot. Thanks to low utility costs, reliable infrastructure and more than 8,000 hours each year of free cooling from outside air, large corporations have established data center operations in the region. </br> This is all good news for local tech talent. While the cost of living is about 7% higher than the national average here, IT salaries have increased over time. Today, IT pros earn a median salary of $96,553. And if you want to put down roots in this mountain state, Colorado Springs is a more budget-friendly choice. Median home prices in Colorado Springs are around $340,000 as opposed to $472,000 in Denver and $800,000 in Boulder.\n\n"
    },
    {
      id: 16,
      city: "Boston",
      state: "Massachussetts",
      city_and_state: "Boston, MA",
      image: "https://i.postimg.cc/sxbjsjfF/boston.jpg",
      num_on_best_paying_cities_list: 41,
      median_software_developer_salary_adj: 102171,
      median_income_of_all_jobs: 67370,
      num_software_developer_jobs: 54140,
      median_home_price: 465000,
      big_companies: ["Raytheon", "IBM", "Deloitte", "MathWorks", "BAE Systems"],
      population_2019: 692600,
      population_change_since_2020: "\"+17.6%\"",
      city_blurb: "The Boston metro area is well-known for its innovative contributions to the life sciences. In fact, local startups are currently generating gene regulation therapies and coronavirus vaccines. The work is important, but it’s not the only work getting noticed here. Investments in innovation have set the area up to grow in the cybersecurity, data analytics and e-commerce markets as well—helping to land Boston at No. 16 on the Tech Town Index. </br> That diversity of industry is one of the reasons why the Boston tech scene is outpacing itself. In the past year, the area advertised for 116,227 open technology positions as compared to 103,890 the previous year. And the talent pipeline stays fresh due to its proximity to a cluster of local universities. For example, the commonwealth of Massachusetts is ranked No. 1 nationally in STEM graduate and professional degrees granted per capita, according to the Massachusetts Technology Collaborative. With a pipeline like that, IT jobs are expected to grow by 8% in the next five years. </br> While the job outlook is promising, a $103,432 median annual salary doesn't go very far in Beantown. In fact, the cost of living in the Boston metro area is approximately 34% higher than the national average. When you adjust that median salary accordingly, it feels more like $77,477. But the walkability of the area in combination with access to great healthcare and a rich history are just a few of the reasons Bostonian tech pros love where they live.\n\n"
    },
    {
      id: 17,
      city: "Baltimore",
      state: "Maryland",
      city_and_state: "Baltimore, MD",
      image: "https://i.postimg.cc/zfLVmcFR/baltimore.jpg",
      num_on_best_paying_cities_list: 20,
      median_software_developer_salary_adj: 107282,
      median_income_of_all_jobs: 57740,
      num_software_developer_jobs: 20400,
      median_home_price: 205600,
      big_companies: ["Northrop Grumman", "Leidos", "General Dynamics", "Booz Allen Hamilton", "Parsons Brinckerhoff"],
      population_2019: 593490,
      population_change_since_2020: "\"-8.9%\"",
      city_blurb: "Climbing a few spots from last year, Baltimore lands at No. 17 on the index this year. The jump could be largely attributed to technology job growth. The metro area posted more than 66,000 available technology jobs within the last year—that's an increase of 8,000+ over the previous year. And while population decline is still an issue in Baltimore—the U.S. Census estimated the city's population at 593,490 as of July 1, 2019, the first time the number has dipped below 600,000 in a century—the tech scene is still growing. In fact, the number of IT jobs is expected to reach nearly 80,000 in just five years, a 7% increase. </br> Where are the jobs coming from? Local experts think rising diversity in tech specialization could account for some of the increase. Baltimore is well-known for its innovations in the tech and life sciences sectors, but programs and facilities with a specific focus seem to be driving jobs here. These up-and-coming markets include medical devices, social enterprise, digital health, cybersecurity and manufacturing labs that support a new wave of consumer products and tech-enabled hardware. In fact, software and application developers are the most sought-after tech talent in the area. </br> And while the cost of living is approximately 31% higher than the national average, the local IT pro has also seen a bit of a pay raise in the past year. The median annual salary is $102,564—about $2,500 more than last year."
    },
    {
      id: 18,
      city: "Madison",
      state: "Wisconsin",
      city_and_state: "Madison, WI",
      image: "https://i.postimg.cc/x8LfjrXc/madison.jpg",
      num_on_best_paying_cities_list: 91,
      median_software_developer_salary_adj: 90238,
      median_income_of_all_jobs: 52890,
      num_software_developer_jobs: 8770,
      median_home_price: 257700,
      big_companies: ["Chandra Technologies", "University of Wisconsin", "Symphony Corporation", "Exact Sciences", "Wisconsin Department of Natural Resources"],
      population_2019: 259680,
      population_change_since_2020: "\"+24.8%\"",
      city_blurb: "Tech job postings are growing here—from 14,617 in 2018 to 16,701 in the past 12 months. And while the tech talent pipeline was once an issue in Madison, as University of Wisconsin graduates tended to move elsewhere post-graduation, the tide is turning and young professionals are seemingly more inclined to stick around these days. Technology companies have taken note of the trend. </br> GrowWire interviewed software company Zendesk about why it chose Madison as its new location, employing nearly 300 employees as of last fall. The company cited its people-first strategy and how Madison fit the bill when it came to opportunities to grow in talent retention and attraction. Health care software giant Epic Systems, employing nearly 10,000 people, is thriving here. According to Inc., the company has seen an explosion of adjacent startups in recent years, including Redox, a health tech company launched by three former Epic employees that now has $50 million in venture funding. </br> With a median tech salary of $82,787, a cost of living 2% higher than the national average, a vibrant, outdoor culture (despite brisk temps in the winter months), and a burgeoning startup scene, Madison is becoming a pretty attractive, non-traditional tech hub for all types of technology talent and companies."
    },
    {
      id: 19,
      city: "San Diego",
      state: "California",
      city_and_state: "San Diego, CA",
      image: "https://i.postimg.cc/W33SPjfw/san-diego.jpg",
      num_on_best_paying_cities_list: 61,
      median_software_developer_salary_adj: 97974,
      median_income_of_all_jobs: 58090,
      num_software_developer_jobs: 19130,
      median_home_price: 590700,
      big_companies: ["Qualcomm", "Northrop Grumman", "Booz Allen Hamilton", "General Atomics", "Intuit"],
      population_2019: 1423851,
      population_change_since_2020: "\"+16.4%\"",
      city_blurb: "The beautiful beach city of San Diego just makes the top 20 this year and it’s in large part due to the city’s efforts to recruit and retain tech talent from Silicon Valley. In fact, one of the most popular (and strategic) messages was a series of billboards over Silicon Valley’s most gridlocked freeways promoting the benefits of moving south. For example: “Today’s surf report: San Diego is better.” </br> But while the lure of the beach is appealing, it’s not the only reason IT pros are considering the San Diego metro area. According to Inc., the San Diego IT sector has seen a three-year revenue growth of 188%. That may be due, in part, to the arrival of tech heavy hitters like Apple, Amazon and Walmart Labs joining local tech giant Qualcomm. But it’s also due to the emerging startup scene focusing on artificial intelligence (AI). In fact, Qualcomm’s corporate venture fund invested $100 million into AI companies. </br> The San Diego and Carlsbad areas posted 66,211 open technology positions last year. And with the tech movers and shakers doing their thing here, the number of IT jobs is estimated to grow by 7% over the next five years. </br> Local tech talent in the aptly nicknamed “Silicon Beach” earn a median annual salary of $103,781 and software application developers continue to be the most in-demand jobs. And while a six-figure paycheck sounds like a good deal, the cost of living in the San Diego metro area is one of the highest on our list—more than 43% higher than the national average. That six-figure income adjusts to just $72,371 when you take cost of living into consideration. But if your California dreams just can’t be matched by any other state, San Diego may be the place to be, beating out San Jose and San Francisco when it comes to affordability."
    },
    {
      id: 20,
      city: "Trenton",
      state: "New Jersey",
      city_and_state: "Trenton, NJ",
      image: "https://i.postimg.cc/Pxg6b92b/trenton.jpg",
      num_on_best_paying_cities_list: 80,
      median_software_developer_salary_adj: 92869,
      median_income_of_all_jobs: 63700,
      num_software_developer_jobs: 4520,
      median_home_price: 240700,
      big_companies: ["Bank of America", "Deloitte", "Anthem Blue Cross", "Briton-Myers Squibb", "Princeton University"],
      population_2019: 83203,
      population_change_since_2020: "\"-2.6%\"",
      city_blurb: "Showing true New Jersey grit, Trenton once again makes an appearance on the index after falling off in 2019. Advertising for nearly 13,000 technology jobs in the past 12 months, the tech economy is on the rise—and the city's location is the biggest draw. Located in central New Jersey on the Delaware River, Trenton is easily accessible to both New York and Philadelphia. </br> That easy access means that Trenton residents may work outside the city and vice versa. In any case, IT jobs in this area are expected to grow by 5% within the next five years. In the capital city, software and app developers along with computer systems analysts are the most in-demand technology jobs—accounting for more than 5,000 of the IT jobs advertised in the area. Bank of America continues to be the top employer posting IT jobs in Trenton, but software consulting firms ZS Associates and DEW Softech are recruiting tech talent this year as well. </br> With Trenton tech talent making a healthy median income of $94,997, the cost of living, which is 23% higher than the U.S. norm, is significantly cheaper than neighboring New York City as well as Tech Towns Boston and Baltimore."
    }
  ]
}